app = "hsc-courses-bot"
primary_region = "sin"

[build]
  # Let Fly auto-detect Node.js

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 10000  # or whatever port your app uses
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    force_https = true

  [[services.http_checks]]
    path = "/health"
    interval = "10s"
    timeout = "2s"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
